<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
	{
        "backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
			
			,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"科技团队管理",
                        "menuJump":"列表",
                        "tableName":"kejituandui"
                    }
                ],
                "menu":"科技团队管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"研发平台管理",
                        "menuJump":"列表",
                        "tableName":"yanfapingtai"
                    }
                ],
                "menu":"研发平台管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"基础设施管理",
                        "menuJump":"列表",
                        "tableName":"jichusheshi"
                    }
                ],
                "menu":"基础设施管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
							"新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"科研成果管理",
                        "menuJump":"列表",
                        "tableName":"keyanchengguo"
                    }
                ],
                "menu":"科研成果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"科技装备管理",
                        "menuJump":"列表",
                        "tableName":"kejizhuangbei"
                    }
                ],
                "menu":"科技装备管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"资料库管理",
                        "menuJump":"列表",
                        "tableName":"ziliaoku"
                    }
                ],
                "menu":"资料库管理"
            }          
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
		    {
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"科技团队管理",
                        "menuJump":"列表",
                        "tableName":"kejituandui"
                    }
                ],
                "menu":"科技团队管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"研发平台管理",
                        "menuJump":"列表",
                        "tableName":"yanfapingtai"
                    }
                ],
                "menu":"研发平台管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"基础设施管理",
                        "menuJump":"列表",
                        "tableName":"jichusheshi"
                    }
                ],
                "menu":"基础设施管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"科研成果管理",
                        "menuJump":"列表",
                        "tableName":"keyanchengguo"
                    }
                ],
                "menu":"科研成果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"科技装备管理",
                        "menuJump":"列表",
                        "tableName":"kejizhuangbei"
                    }
                ],
                "menu":"科技装备管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"资料库管理",
                        "menuJump":"列表",
                        "tableName":"ziliaoku"
                    }
                ],
                "menu":"资料库管理"
            }          
        ],
        "frontMenu":[

        ],
        "roleName":"应急科技人才",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
